<?php
/**
 * @file
 * TM Lazyload Install
 *
 * @author: Daniel Honrade http://drupal.org/user/351112
 *
 */


/**
 * Implements hook_install().
 */
function tm_lazyload_install() {
	// Make sure this module called last
	// to override any form provided by other modules
	db_query( "UPDATE {system} SET weight = 3000 WHERE name = 'tm_lazyload'" );
}


/**
 * Implements hook_uninstall().
 */
function tm_lazyload_uninstall() {
	variable_del( 'tm_lazyload' );
}